#!/bin/bash

# shit in here is just for vim to use
shopt -s expand_aliases

. $HOME/src/z/z.sh

export NODE_PATH=/home/jtm/.config/nvm/versions/node/v20.17.0/lib/node_modules
# alias yapf='PYTHONPATH=$HOME/src/yapf python3 $HOME/src/yapf/yapf'
