#!/bin/bash

REPO=/home/jared/src/vim
PY2=/usr/lib/python2.7/config-x86_64-linux-gnu
PY3=/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu
RUBY=/usr/bin/ruby
YOU="skeletor"

if cd $REPO; then git pull; else git clone https://github.com/vim/vim.git $REPO; fi

sudo rm -rf /usr/local/share/vim /usr/bin/vim

cd $REPO

make distclean

./configure \
--enable-multibyte \
--enable-perlinterp=dynamic \
--enable-rubyinterp=dynamic \
--with-ruby-command=$RUBY \
--enable-pythoninterp=dynamic \
--with-python-config-dir=$PY2 \
--enable-python3interp \
--with-python3-config-dir=$PY3 \
--enable-luainterp \
--with-luajit \
--enable-cscope \
--enable-gui=auto \
--with-features=huge \
--with-x \
--enable-fontset \
--enable-largefile \
--disable-netbeans \
--with-compiledby="$YOU" \
--enable-fail-if-missing

make -j 4 && sudo make -j 4 install
