#!/usr/bin/env bash

VIM=$HOME/.vim

help="$(basename $0) [OPTION]

  - setup           setup vimmies
  - update          update submodules
  - install <url>   install submodule
  - remove <name>   remove submodule
"

_exit() { echo $1 && exit 0; } # clean msg & exit

_setup() {
  git submodule update --init --recursive
  mkdir -p $VIM/junk/{backup,swp,undo,view}
}

_update() {
  git submodule update --remote --merge
}

_install() {
  if [[ -z $2 ]]; then _exit "Specify the submodule URL"; fi
  cd $VIM/pack/plugins/start
  git submodule add --force $2
  cd -
}

_remove() {
  if [[ -z $2 ]]; then _exit "Specify the submodule dirname"; fi
  if [[ ! -d $VIM/pack/plugins/start/$2 ]]; then _exit "Submodule doesn't exist"; fi
  git submodule deinit -f $VIM/pack/plugins/start/$2
  git rm -f $VIM/pack/plugins/start/$2
  rm -Rf $VIM/.git/modules/pack/plugins/start/$2
}

if [[ $(type -t _$1) = 'function' ]]; then
    _$1 $*
else
  echo "$help"
fi
